primitives:
    - copper ore: 4
    - tin ore: 4
    - sticky resin: 3
    - UU-matter: 500
    - uranium ore: 25

crafts: 
    - coal dust:
        machine: macerator
        ingredients: [coal]
    - iron dust:
        machine: macerator
        makes: 2
        ingredients: [iron ore]
    - iron:
        machine: furnace
        ingredients: [iron dust]
    - refined iron:
        machine: furnace
        ingredients: [iron]
    - tin dust:
        machine: macerator
        makes: 2
        ingredients: [tin ore]
    - copper dust:
        machine: macerator
        makes: 2
        ingredients: [copper ore]
    - gold dust:
        machine: macerator
        makes: 2
        ingredients: [gold ore]
    - gold ingot:
        machine: furnace
        ingredients: [gold dust]
    - tin ingot:
        machine: furnace
        ingredients: [tin ore]
    - tin ingot:
        machine: furnace
        ingredients: [tin dust]
    - copper ingot:
        machine: furnace
        ingredients: [copper dust]
    - copper ingot:
        machine: furnace
        ingredients: [copper ore]
    - bronze: # NOTE: forestry daje alternatywną
        machine: furnace
        ingredients: [bronze dust]
    - bronze dust: [copper dust*3, tin dust]
    - rubber:
        machine: furnace
        ingredients: [sticky resin]
    - rubber:
        machine: extractor
        makes: 3
        ingredients: [sticky resin]
    - cell:
        makes: 16
        ingredients: [tin ingot*4]
    - carbon fibers: [coal dust*4]
    - combined carbon fibers: [carbon fibers, carbon fibers]
    - carbon plate:
        machine: compressor
        ingredients:
          - combined carbon fibers
    - mixed metal ingot:
        makes: 2
        ingredients:
          - refined iron*3
          - bronze*3
          - tin ingot*3
    - advanced alloy:
        machine: compressor
        ingredients: [mixed metal ingot]
    - iridium plate:
      - iridium*4
      - advanced alloy*4
      - diamond
    - reinforced glass:
        makes: 7
        ingredients:
          - glass*7
          - advanced alloy*2
    - iron fence: [refined iron*6]
