cluster: ic2_adv_sol
#require ic2
# mod_ver: 3.3.2

crafts:
- sunnarium:
    ingredients: [glowstone*3, UU-matter*6]
    shape: U U U g g g U U U
- sunnarium alloy:
    ingredients: [sunnarium, iridium plate**]
    shape: i i i i s i i i i
- advanced solar panel: # shape name conflict
    ingredients: [reinforced glass*3, solar panel, advanced alloy*2, advanced machine, advanced circuit*2]
- hybrid solar panel: # shape name conflict
    ingredients: [lapis block, carbon plate*2, iridium plate*2, advanced solar panel, advanced circuit*2, sunnarium]
- hybrid solar panel:
    ingredients: [ultimate hybrid solar panel]
    makes: 8
- ultimate hybrid solar panel:
    ingredients: [hybrid solar panel*8, advanced circuit]
    shape: h h h h a h h h h
- ultimate hybrid solar panel:
    ingredients: [lapis block, hybrid solar panel, coal chunk*3, sunnarium alloy]
    shape: ~ l ~ c h c s c s

# TODO: think about implementation of expensive types of these